{
 "title": "NestJS Base Logs",
 "description": "Monitor de Logs - NestJS Base",
 "tags": [
  "loki",
  "base",
  "nestjs"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   { "name": "label_name", "label": "Label Name", "query": "label_names()" },
   { "name": "label_value", "label": "Label Value", "query": "label_values($label_name)" },
   {
    "name": "job",
    "label": "Job",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Estadísticas generales", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Peticiones",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (count_over_time({$label_name=~\"$label_value\", job=~\"$job\"} | json | context=\"request\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Total Respuestas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (count_over_time({$label_name=~\"$label_value\", job=~\"$job\"} | json | context=\"response\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Errores de tipo 400",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (count_over_time({$label_name=~\"$label_value\", job=~\"$job\"} | json | context=\"http-exception\" | codigo<500 [$__interval]))"
    }
   ]
  },
  {
   "title": "Errores de tipo 500",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (count_over_time({$label_name=~\"$label_value\", job=~\"$job\"} | json | context=\"http-exception\" | codigo>=500 [$__interval]))"
    }
   ]
  },
  {
   "title": "Cantidad de registros",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (count_over_time({$label_name=~\"$label_value\", job=~\"$job\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Tamaño de registros",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (bytes_over_time({$label_name=~\"$label_value\", job=~\"$job\"} [$__interval]))"
    }
   ]
  },
  { "title": "Estadísticas por usuario", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Accesos por usuario",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(usuario, tipo) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\"} | json | context = `authentication` | msg = `Ingresó al sistema` | usuario != \"\"\n [$__interval]))",
     "legendFormat": "{{ username }}"
    }
   ]
  },
  {
   "title": "Cierres de sesión por usuario",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (usuario, msg) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\"} | json | context=\"authentication\" | msg=\"Salió del sistema\" [$__interval]))",
     "legendFormat": "{{ username }}"
    }
   ]
  },
  {
   "title": "Errores por usuario",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (codigo, usuario, mensaje) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\"} | json | context=\"http-exception\" [$__interval]))",
     "legendFormat": "{{ username }}"
    }
   ]
  },
  { "title": "Detalle de errores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Errores de tipo 400",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{$label_name=~\"$label_value\", job=~\"$job\"} | json | context=\"\" | level=40"
    }
   ]
  },
  {
   "title": "Errores de tipo 500",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{$label_name=~\"$label_value\", job=~\"$job\"} | json | context=\"\" | level=50"
    }
   ]
  }
 ]
}